import Header from '@/components/Header';
import { MSWComponent } from '@/components/MSWComponent';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

const didot = localFont({
  src: '../public/fonts/Didot.otf',
  display: 'swap',
  variable: '--font-didot',
});

export const metadata: Metadata = {
  title: 'CoatyCloset',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={didot.variable}>
      <body className={pretendard.className}>
        <MSWComponent>
          <ToastContainer
            position="top-center"
            autoClose={700}
            hideProgressBar
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          <Header />
          {children}
          {/* 로그인 상태에 따라서 렌더링 할 예정 */}
        </MSWComponent>
      </body>
    </html>
  );
}
