import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { MSWComponent } from "@/components/MSWComponent";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const didot = localFont({
  src: "../public/fonts/Didot.otf",
  display: "swap",
  variable: "--font-didot",
});

export const metadata: Metadata = {
  title: "CoatyCloset",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={didot.variable}>
      <body className={pretendard.className}>
        <MSWComponent>
          <Header />
          {children}
          {/* 로그인 상태에 따라서 렌더링 할 예정 */}
          <Footer />
        </MSWComponent>
      </body>
    </html>
  );
}
